### ISSUE TITLE
iOS targets

### ISSUE THREAD

**Issue by terrakok** [piruin/geok#10]
It would be nice if you published ios targets 😃 
But you can do it from macOS only.
https://repo1.maven.org/maven2/io/github/piruin/

**Comment by piruin** [comment]
Is it needs? Because `geok` has no iOS specify code, MultiPlatform should be enough. Correct me if I am misunderstood.

**Comment by terrakok** [comment]
You are right. But you should publish ios artifacts for projects with ios target. There isn't way to use common part without published artifacts for all platforms.

**Comment by terrakok** [comment]
https://discuss.kotlinlang.org/t/is-it-possible-to-use-common-kotlin-library-not-multiplatform-in-kotlin-multiplatform-commonmain-jvm/17441

**Comment by piruin** [comment]
ios target has been published as `1.2.2`. 🍺

**Comment by terrakok** [comment]
I added to https://github.com/terrakok/kmm-awesome/blob/master/README.MD#-utils
