### ISSUE TITLE
Could not resolve me.piruin:geok:1.0.0.

### ISSUE THREAD

**Issue by LazarIliev** [piruin/geok#2]
We have added this plugin to our project and it was working. But from a week ago is not working. The build is not passing and fails with:

> Could not resolve me.piruin:geok:1.0.0.
         > Could not get resource 'https://dl.bintray.com/blazei/maven/me/piruin/geok/1.0.0/geok-1.0.0.pom'.
            > Could not GET 'https://dl.bintray.com/blazei/maven/me/piruin/geok/1.0.0/geok-1.0.0.pom'. Received status code 403 from server: Forbidden

Can you please provide us with the latest status of the plugin and if there are some new restrictions on the official repo.

**Comment by piruin** [comment]
@LazarIliev 
Because [Bintray](https://bintray.com/) service has now been shut down.  Please try to download from [Jitpack](https://jitpack.io/#piruin/geok/1.0.0) instead (I'm not sure if it still works).

**Comment by LazarIliev** [comment]
@piruin 
Thank you. I get it from Jitpack and it is working.
