### ISSUE TITLE
MavenCentral publication

### ISSUE THREAD

**Issue by terrakok** [piruin/geok#7]
What do you think about MavenCentral? It's stable and safe service.
Here is a good article
https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

It's about Android library but there aren't differences for multi platform.
If you want I'll help with configuration 😃

**Comment by piruin** [comment]
It would be great if you help with the configuration.

**Comment by terrakok** [comment]
https://github.com/piruin/geok/pull/8

**Comment by piruin** [comment]
@terrakok `geok` now available on MavenCentral! Thank for your help
